### ISSUE TITLE
https://dl.bintray.com/subclipse/releases/m2e/1.0.x/ not available

### ISSUE THREAD

**Issue by jflefebvre06** [subclipse/m2e#1]
Hello,

https://dl.bintray.com/subclipse/releases/m2e/1.0.x/ is now  available, could you please provide another URL

**Comment by markphip** [comment]
Bintray shutdown, the Subclipse update site is now here:   https://subclipse.github.io/updates/

**Comment by jflefebvre06** [comment]
Thanks 

Readme file must be updated 

```An Eclipse p2 repository has been posted to the following location:

https://dl.bintray.com/subclipse/releases/m2e/1.0.x/
Want to contribute? Great! Just send me pull requests and we can review them.```
